routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/','HomeController@index')->name('home');
Route::get('/admin', function () {
    return view('adminhome');
});

Route::get('/', function () {
    return view('welcome');
});


Route::get('/1', function () {
    return view('demo');
});




Auth::routes();
Route::resource('admin','AdminController');
Route::resource('trainer','TrainerController');
Route::resource('departments','DepartmentsController');
Route::resource('trainee','TraineeController');
Route::get('/home', 'HomeController@index')->name('home');

resources/views/dnotuse/create.blade.php
<!-- Stored in resources/views/child.blade.php -->

@extends('layouts.app')

@section('title', 'Departments')

@section('content')
    <div class="card">        
        {{ Form::open(['route' => 'departments.store']) }}
        <div class="card-content">
            <span class="card-title">
                Add Detail                
            </span>
            <div class="row">
                <div class="col s12 l4">
                    <div class="input-field">
                        <input type='text' name="name" id="name" />
                        <label for="name">Department Name</label>
                    </div>                    
                </div>
            </div>
        </div>
        <div class="card-action">
            {{ Form::submit('Add', ['class' => 'btn pink white-text']) }}
        </div>
        {{ Form::close() }}
    </div>
@endsection

resources/views/dnotuse/index.blade.php
<!-- Stored in resources/views/child.blade.php -->

@extends('layouts.app')

@section('title', 'Departments')

@section('content')
    <h1 class="blue-text">Departments</h1>
    <a class="btn blue white-text" href={{ route('departments.create') }}>
        <i class="material-icons left">add</i>
        New
    </a>
    <table>
        <thead>
            <tr>
                <th>Ref #</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($departments as $department) { ?>
                <tr>
                    <td>{{ $department->id }}</td>
                    <td>{{ $department->name }}</td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
@endsection

resources/views/dnotuse/table.blade.php
<!-- Stored in resources/views/child.blade.php -->

@extends('layouts.mat')

@section('title', 'Departments')

@section('content')
<a class="btn blue white-text" href={{ route('departments.table') }}>
<table>
        <thead>
          <tr>
              <th>Name</th>
              <th>Item Name</th>
              <th>Item Price</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>Alvin</td>
            <td>Eclair</td>
            <td>$0.87</td>
          </tr>
          <tr>
            <td>Alan</td>
            <td>Jellybean</td>
            <td>$3.76</td>
          </tr>
          <tr>
            <td>Jonathan</td>
            <td>Lollipop</td>
            <td>$7.00</td>
          </tr>
        </tbody>
      </table>
            
@endsection